accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    
    path('signup',views.signup , name='signup' ),
    path('profile/<slug:slug>',views.profile , name='profile' ),
    path('edit_profile/<slug:slug>/', views.edit_profile , name='edit_profile'),

]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add-contact/', views.addContact, name='add-contact'),
    path('edit-contact/<str:pk>', views.editContact, name='edit-contact'),
    path('delete/<str:pk>', views.deleteContact, name='delete'),
    path('profile/<str:pk>', views.contactProfile, name='profile')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import datetime
from django_countries.fields import CountryField
from django.utils.text import slugify
from django.urls import reverse
from django.db.models.signals import post_save
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)
    image = models.ImageField(_("image"), upload_to='profile_img', blank=True, null=True)
    country = CountryField()
    address = models.CharField(max_length=100)
    join_date = models.DateTimeField(_("join date"),default = datetime.datetime.now)

    def save(self , *args , **kwargs):
        if not self.slug :
            self.slug = slugify(self.user.username)
        super(Profile , self).save( *args , **kwargs)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return  '%s' %(self.user)

    def get_absolute_url(self):
        return reverse("accounts:edit_profile", kwargs={"slug": self.slug})



def create_profile(sender , **kwargs):
    print(kwargs)
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile , sender=User)        

contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    full_name = models.CharField(max_length=250)
    relationship = models.CharField(max_length=250)
    email = models.EmailField(max_length=254)
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=1000)

    def __str__(self):
          return self.full_name

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [ 'username','first_name','last_name','email']



class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['image','country','address']

accounts/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from django.contrib.auth import login , authenticate
from .models import Profile
from .forms import UserForm , ProfileForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            user = authenticate(username=username,password=password)
            login(request, user)
            return redirect('/products')

    else:
        form = UserCreationForm()

    context = {'form' : form}
    return render(request , 'registration/signup.html' , context)


@login_required(login_url='/accounts/login/')
def profile(request , slug):
    profile = get_object_or_404(Profile , slug=slug)
    context = {'profile' : profile}
    return render(request , 'profile.html' , context)


@login_required(login_url='login')
def edit_profile(request,slug):
    
    my_profile   = Profile.objects.get(user=request.user)
    user_form    =  UserForm(instance=request.user)
    profile_form =  ProfileForm(instance=my_profile)

    if request.method == 'POST':

           user_form     =  UserForm(request.POST,instance=request.user)
           profile_form  =  ProfileForm(request.POST,request.FILES,instance=my_profile)

           if user_form.is_valid() and profile_form.is_valid():
               user_form.save()
               new_profile_form = profile_form.save(commit=False)
               new_profile_form.user = request.user
               new_profile_form.save()
               return redirect('accounts:profile',slug=slug)
    
           else :
                user_form    =  UserForm(request.POST,instance=request.user)
                profile_form =   ProfileForm(request.POST,request.FILES,instance=my_profile)

    context = {'user_form':user_form,'profile_form':profile_form}
    return render(request,'edit_profile.html',context)    

contact/views.py
from django.shortcuts import render,redirect
from .models import Contact
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    contacts = Contact.objects.all()
    search_input = request.GET.get('search-area')
    if search_input:
        contacts = Contact.objects.filter(full_name__icontains=search_input)
    else:
        contacts = Contact.objects.all()
        search_input = ''
    return render(request, 'index.html', {'contacts':contacts})

@login_required(login_url='/accounts/login/')    
def addContact(request):
    if request.method == 'POST':
        new_contact = Contact(
            full_name=request.POST['fullname'],
            relationship=request.POST['relationship'],
            email=request.POST['email'],
            phone_number=request.POST['phone-number'],
            address=request.POST['address'],
            )
        new_contact.save()
        return redirect('/')


    return render(request,'new.html')

@login_required(login_url='/accounts/login/')
def editContact(request, pk):
    contact = Contact.objects.get(id=pk)

    if request.method == 'POST':
        contact.full_name = request.POST['fullname']
        contact.relationship = request.POST['relationship']
        contact.email = request.POST['email']
        contact.phone_number = request.POST['phone-number']
        contact.address = request.POST['address']
        contact.save()

        return redirect('/profile/'+str(contact.id))
    return render(request, 'edit.html', {'contact': contact})     

@login_required(login_url='/accounts/login/')
def deleteContact(request, pk):
    contact = Contact.objects.get(id=pk)

    if request.method == 'POST':
        contact.delete()
        return redirect('/')

    return render(request, 'delete.html', {'contact': contact})    

@login_required(login_url='/accounts/login/')
def contactProfile(request, pk):
    contact = Contact.objects.get(id=pk)
    return render(request, 'contact-profile.html', {'contact':contact})     

accounts/templates/edit_profile.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% load static %}

{% block body %}

  <!--Main layout-->
      <main class="mt-3 pt-4">
            <div class="container dark-grey-text mt-5" >
                <h4 style="margin-left: 480px; font-weight: bold;" class="text-primary" > Edit My Profile </h4>
                <form method="POST" enctype="multipart/form-data" class="col-sm-6" style="margin: auto;">
                    {% csrf_token %}
                    {% bootstrap_form user_form %}
                    {% bootstrap_form profile_form %}
                    <button class="boxed-btn3 w-100" type="submit"> Save Changes </button>
                </form>
            </div>
      </main>
<!--Main layout-->

{% endblock body %}

accounts/templates/profile.html
{% extends 'base.html' %}

{% load static %}
{% block body %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          
          {% if profile.image %}
              <img src="{{profile.image.url}}" class="img-fluid" alt="">
        {% else %}
             <img src="{% static 'site_static/img/user-default.png' %}" class="img-fluid" alt="">
        {% endif %}

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <p class="lead font-weight-bold">{{profile}}</p>
            <p class="lead">
                  <p>{{profile.user.email}}</p>
                  <p>{{profile.country}} - {{profile.address}}</p>
            </p>

              <!-- Default input -->
              <a class="btn btn-primary btn-md my-0 p" type="submit">Edit My Profile
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>
      <!--Grid row-->
     
  </main>
  <!--Main layout-->
  {% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>SOUQ</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'site_static/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'site_static/css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'site_static/css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'site_static/css/style.css' %}" rel="stylesheet">
  <style type="text/css">
   html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="" >
        <strong class="blue-text">Authentication</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
       

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle"></i>Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href=""> My Profile</a>
                  <a class="dropdown-item" href="">Edit My Profile</a>
                  <a class="dropdown-item" href="">Change Password</a>
                  <div class="dropdown-divider"></div>
                  
                  
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
              </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link border border-light rounded waves-effect">
              <i class="fas fa-sign-in-alt mr-2"></i>Login
            </a>
          </li>
          <li class="nav-item">
              <a href="{% url 'accounts:signup' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fas fa-user-plus"></i>Signup
              </a>
            </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->


  <!--Main layout-->
  {% block body  %}
  {% endblock body  %}


  <!--Main layout-->

  

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'site_static/js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'site_static/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'site_static/js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

templates/contact-profile.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style-profile.css'%}">
	
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Contact Profile</title>
</head>
<body>

	<div class="container">
		<header class="hero">
			<a href="{%url 'index'%}">
				<i  class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">{{contact.full_name | title}}</h1>
				<p  class="relationship">{{contact.relationship | title}}</p>
			</div>
		</header>

		<section class="contact-info">

			<div class="info-line">
				<i class="fas fa-phone icon-gradient"></i>
				<p class="phone-number">{{contact.phone_number}}</p>
			</div>

		

			

			

			<div class="info-line">
				<i class="fas fa-envelope icon-gradient"></i>
				<p class="email">{{contact.email}}</p>
			</div>

			

			<div class="info-line">
				<i id="location" class="fas fa-map-marker-alt icon-gradient"></i>
				<p class="address">{{contact.address}}</p>
			</div>
		</section>

		<a href="{% url 'edit-contact' contact.id %}">
			<section class="edit-contact">
				<div class="edit-button">
					<i class="fas fa-cog icon-gradient"></i>
				</div>
			</section>
		</a>
	</div>

</body>
</html>

templates/delete.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style-delete.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Delete Contact</title>
</head>

<body>
	<div class="container">
		<header class="hero">
			<a href="{% url 'edit-contact' contact.id %}">
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">{{ contact.full_name | title }}</h1>
				<p class="relationship-hero">{{ contact.relationship | title }}</p>
			</div>
		</header>

		<section class="delete-container">
			<p>Are you sure you want to delete this contact?</p>

			<form method='POST'>
				{% csrf_token %}
				<div class="delete-contact">
					<i class="fas fa-trash delete-icon"></i>
					<input class="delete-button" type="submit" value='Delete Contact' />
				</div>
			</form>

		</section>
	</div>

</body>

</html>

templates/edit.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style-edit.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Edit Contact</title>
</head>

<body>

	<div class='container'>
		<header class="hero">
			<a href="{% url 'profile' contact.id %}">
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">{{ contact.full_name | title }}</h1>
				<p class="relationship-hero">{{ contact.relationship | title }}</p>
			</div>
		</header>

		<form action="" method="POST">
			{% csrf_token %}
			<section class="contact-info">

				<div class="info-line">
					<i class="fas fa-phone icon-gradient"></i>
					<input type="text" class="type" name="fullname" placeholder="Full Name"
						value="{{ contact.full_name | title }}">
				</div>

				<div class="info-line">
					<i class="fas fa-user-circle icon-gradient"></i>
					<input type="text" class="type" name="relationship" placeholder="Relationship"
						value="{{ contact.relationship | title }}">
				</div>



				<div class="info-line">
					<i class="fas fa-sms icon-gradient"></i>
					<input type="text" class="type" name="phone-number" placeholder="Phone Number"
						value="{{ contact.phone_number }}">
				</div>



				<div class="info-line">
					<i class="fas fa-envelope icon-gradient"></i>
					<input type="text" class="type" name="email" placeholder="Email" value="{{ contact.email }}">
				</div>



				<div class="info-line">
					<i class="fas fa-map-marker-alt icon-gradient location"></i>
					<input type="text" class="type" name="address" placeholder="Address" value="{{ contact.address }}">
				</div>


			</section>

			<section class="button-container">
				<div class="update-contact">
					<i class="fas fa-check-circle icon-gradient"></i>
					<button class="button">Save Contact</button>
				</div>
			</section>
		</form>

		<section class="button-container">

			<a href="{% url 'delete' contact.id %}">
				<div class="update-contact">
					<i class="fas fa-trash icon-gradient"></i>
					<button class="button">Delete Contact</button>
				</div>
			</a>

		</section>
	</div>

</body>


</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>

	<title>Contact Form</title>
</head>
<body>

	<div class="container">
		<!--  SEARCH FORM -->
		<header class="header">
			
			<form class="search-bar" action="" method="GET">
				<input type="search-name" class="contact-search" name="search-area" placeholder="Search" value="{{search_input}}">
			</form>

			<!--  ADD-CONTACT BUTTON/ICON -->
			<a href="{% url 'add-contact' %}"><i class="fas fa-plus-circle add"></i></a>
		</header>

		<!--  CONTACT LIST -->
		<section class="contacts-library">
			<ul class="contacts-list">
				{% for contact in contacts %}
				<a href="{% url 'profile' contact.id %}">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">{{contact.full_name | title}}</p>
							<p class="relationship">{{contact.relationship | title}}</p>
						</li>

						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>
				{% empty %}
				<h3 style="color:#fff;padding:20px;">No contacts found..</h3>
				{% endfor %}

				
			</ul>
		</section>
	</div>

</body>
</html>

templates/new.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style-edit.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Edit Contact</title>
</head>

<body>
	<div class='container'>
		<header class="hero">

			<a href={% url 'index' %}>
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>

			<div class="hero-info">
				<h1 class="name">New Contact</h1>
			</div>
		</header>

		<form action="" method="POST">
			{% csrf_token %}
			<section class="contact-info">

				<div class="info-line">
					<i class="fas fa-phone icon-gradient"></i>
					<input type="text" class="type" name="fullname" placeholder="Full Name">
				</div>

				<div class="info-line">
					<i class="fas fa-user-circle icon-gradient"></i>
					<input type="text" class="type" name="relationship" placeholder="Relationship">
				</div>



				<div class="info-line">
					<i class="fas fa-sms icon-gradient"></i>
					<input type="text" class="type" name="phone-number" placeholder="Phone Number">
				</div>




				<div class="info-line">
					<i class="fas fa-map-marker-alt icon-gradient location"></i>
					<input type="text" class="type" name="address" placeholder="Address">
				</div>


				<div class="info-line">
					<i class="fas fa-envelope icon-gradient location"></i>
					<input type="text" class="type" name="email" placeholder="Email">
				</div>



			</section>

			<section class="button-container">


				<div class="update-contact">
					<i id="save" class="fas fa-check-circle icon-gradient"></i>
					<button type=" submit" class="button">Save Contact</button>
				</div>
			</section>


		</form>
	</div>

</body>

</html>